# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ShiftLeft NextGen Static Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  NG_SAST_Build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with: 
        java-version: 11.0.2
    - name: Build with Maven
      run: mvn compile package
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with: 
        java-version: 1.8
    - name: NextGen Static Analysis
      run: ${GITHUB_WORKSPACE}/sl analyze --app Vulnado-GitHubAction --tag branch=${{ github.head_ref }} --java --cpg target/vulnado-0.0.1-SNAPSHOT.jar
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Parse Results
      run: |
        curl -X GET https://www.shiftleft.io/api/v4/orgs/${{SHIFTLEFT_ORG_ID}}/apps/Vulnado-GitHubAction/findings -H "Accept: application/json" -H "Authorization: Bearer ${{SHIFTLEFT_API_TOKEN}}" | jq -c '.response.findings[] | {id: .id, title: .title}'
